import type { Metadata } from 'next'
import { Inter, Nunito,Poppins } from 'next/font/google'
import NavBar from '@/Components/NavBar'
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ subsets: ['latin'], weight:['400','700']})

export const metadata: Metadata = {
  title: 'ProDesign Kitchens',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={poppins.className}>
        <NavBar/> 
        <Toaster position='top-center' toastOptions={{duration:5000 }}/>
        {children}
     
        </body>
    </html>
  )
}
